### ISSUE TITLE
azure_rm_resourcegroup module resource-group-name pattern error

### ISSUE THREAD

**Issue by Abhijeet-create** [ansible-collections/community.azure#10]
##### SUMMARY

not able to  create resource_group in azure as module throws error "ValidationError: Parameter 'resource_group_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'."

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_resourcegroup
##### ANSIBLE VERSION

```paste below
ansible 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python3.6/site-packages/ansible
  executable location = /root/.local/bin/ansible
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Centos 7
##### STEPS TO REPRODUCE

pip3 install ansible
pip3 install ansible[azure]
create ~/.azure/credentials file
save azure service principles in credentials file as shown below

[default]
subscription_id=xxxx-xxxx-xxxx-xxxx
client_id=xxxx-xxxx-xxxx-xxxx
secret=xxxxxxxxxxxx
tenant=xxxx-xxxx-xxxx-xxxx

```yaml
---
-
  connection: local
  gather_facts: false
  hosts: localhost
  tasks:
  -
    azure_rm_resourcegroup:
        location: "eastus"
        name: "demo"
        name: Create resource group
    register: info
  - debug:
      var: info

```

##### EXPECTED RESULTS

Resource group  "demo" should be created  in azure 
##### ACTUAL RESULTS

ansible-playbook 2.9.13
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python3.6/site-packages/ansible
  executable location = /root/.local/bin/ansible-playbook
  python version = 3.6.8 (default, Nov 16 2020, 16:55:22) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
script declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
auto declined parsing /etc/ansible/hosts as it did not pass its verify_file() method
Parsed /etc/ansible/hosts inventory source with ini plugin
[WARNING]: While constructing a mapping from /etc/ansible/azure/create-resource-group.yaml, line 9, column 9, found a duplicate dict key (name). Using last defined
value only.
Loading callback plugin default of type stdout, v2.0 from /root/.local/lib/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: create-resource-group.yaml ***********************************************************************************************************************************
Positional arguments: create-resource-group.yaml
verbosity: 4
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/etc/ansible/hosts',)
forks: 5
1 plays in create-resource-group.yaml

PLAY [localhost] *******************************************************************************************************************************************************
META: ran handlers

TASK [azure_rm_resourcegroup] ******************************************************************************************************************************************
task path: /etc/ansible/azure/create-resource-group.yaml:8
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir "` echo /root/.ansible/tmp/ansible-tmp-1610036882.6337843-84124-33472258401151 `" && echo ansible-tmp-1610036882.6337843-84124-33472258401151="` echo /root/.ansible/tmp/ansible-tmp-1610036882.6337843-84124-33472258401151 `" ) && sleep 0'
Using module file /root/.local/lib/python3.6/site-packages/ansible/modules/cloud/azure/azure_rm_resourcegroup.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-84116meua5oh2/tmp694e15gv TO /root/.ansible/tmp/ansible-tmp-1610036882.6337843-84124-33472258401151/AnsiballZ_azure_rm_resourcegroup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1610036882.6337843-84124-33472258401151/ /root/.ansible/tmp/ansible-tmp-1610036882.6337843-84124-33472258401151/AnsiballZ_azure_rm_resourcegroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1610036882.6337843-84124-33472258401151/AnsiballZ_azure_rm_resourcegroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1610036882.6337843-84124-33472258401151/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1610036882.6337843-84124-33472258401151/AnsiballZ_azure_rm_resourcegroup.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-tmp-1610036882.6337843-84124-33472258401151/AnsiballZ_azure_rm_resourcegroup.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-tmp-1610036882.6337843-84124-33472258401151/AnsiballZ_azure_rm_resourcegroup.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible.modules.cloud.azure.azure_rm_resourcegroup', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure_rm_resourcegroup_payload_q7jzlwf4/ansible_azure_rm_resourcegroup_payload.zip/ansible/modules/cloud/azure/azure_rm_resourcegroup.py", line 291, in <module>
  File "/tmp/ansible_azure_rm_resourcegroup_payload_q7jzlwf4/ansible_azure_rm_resourcegroup_payload.zip/ansible/modules/cloud/azure/azure_rm_resourcegroup.py", line 287, in main
  File "/tmp/ansible_azure_rm_resourcegroup_payload_q7jzlwf4/ansible_azure_rm_resourcegroup_payload.zip/ansible/modules/cloud/azure/azure_rm_resourcegroup.py", line 169, in __init__
  File "/tmp/ansible_azure_rm_resourcegroup_payload_q7jzlwf4/ansible_azure_rm_resourcegroup_payload.zip/ansible/module_utils/azure_rm_common.py", line 348, in __init__
  File "/tmp/ansible_azure_rm_resourcegroup_payload_q7jzlwf4/ansible_azure_rm_resourcegroup_payload.zip/ansible/modules/cloud/azure/azure_rm_resourcegroup.py", line 183, in exec_module
  File "/usr/local/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2017_05_10/operations/resource_groups_operations.py", line 267, in get
    'resourceGroupName': self._serialize.url("resource_group_name", resource_group_name, 'str', max_length=90, min_length=1, pattern=r'^[-\w\._\(\)]+$'),
  File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 594, in url
    data = self.validate(data, name, required=True, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 674, in validate
    raise ValidationError(key, name, value)
msrest.exceptions.ValidationError: Parameter 'resource_group_name' must conform to the following pattern: '^[-\\w\\._\\(\\)]+$'.
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1610036882.6337843-84124-33472258401151/AnsiballZ_azure_rm_resourcegroup.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1610036882.6337843-84124-33472258401151/AnsiballZ_azure_rm_resourcegroup.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1610036882.6337843-84124-33472258401151/AnsiballZ_azure_rm_resourcegroup.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.cloud.azure.azure_rm_resourcegroup', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_q7jzlwf4/ansible_azure_rm_resourcegroup_payload.zip/ansible/modules/cloud/azure/azure_rm_resourcegroup.py\", line 291, in <module>\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_q7jzlwf4/ansible_azure_rm_resourcegroup_payload.zip/ansible/modules/cloud/azure/azure_rm_resourcegroup.py\", line 287, in main\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_q7jzlwf4/ansible_azure_rm_resourcegroup_payload.zip/ansible/modules/cloud/azure/azure_rm_resourcegroup.py\", line 169, in __init__\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_q7jzlwf4/ansible_azure_rm_resourcegroup_payload.zip/ansible/module_utils/azure_rm_common.py\", line 348, in __init__\n  File \"/tmp/ansible_azure_rm_resourcegroup_payload_q7jzlwf4/ansible_azure_rm_resourcegroup_payload.zip/ansible/modules/cloud/azure/azure_rm_resourcegroup.py\", line 183, in exec_module\n  File \"/usr/local/lib/python3.6/site-packages/azure/mgmt/resource/resources/v2017_05_10/operations/resource_groups_operations.py\", line 267, in get\n    'resourceGroupName': self._serialize.url(\"resource_group_name\", resource_group_name, 'str', max_length=90, min_length=1, pattern=r'^[-\\w\\._\\(\\)]+$'),\n  File \"/usr/local/lib/python3.6/site-packages/msrest/serialization.py\", line 594, in url\n    data = self.validate(data, name, required=True, **kwargs)\n  File \"/usr/local/lib/python3.6/site-packages/msrest/serialization.py\", line 674, in validate\n    raise ValidationError(key, name, value)\nmsrest.exceptions.ValidationError: Parameter 'resource_group_name' must conform to the following pattern: '^[-\\\\w\\\\._\\\\(\\\\)]+$'.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```paste below

```

**Comment by Abhijeet-create** [comment]
My mistake I didn't recognise the indentation of task name, the playbook should be like as below and it will work fine.

![image](https://user-images.githubusercontent.com/56815039/103922430-bf55f780-5139-11eb-9a01-97dc52022757.png)
